### ISSUE TITLE
Footer on android does not work

### ISSUE THREAD

**Issue by jaxgeller** [BraveUX/braveux#141]
![screenshot_2014-12-12-10-53-58](https://cloud.githubusercontent.com/assets/4494509/5414524/af56deca-81ed-11e4-8031-4ae8d14ab792.png)

**Comment by callmecavs** [comment]
![screenshot 2015-01-26 15 45 16](https://cloud.githubusercontent.com/assets/2293641/5908076/56786f64-a572-11e4-97c9-8a2467d0ca5d.png)

the problem lies within this screenshot. this is a chrome hack/fix we used to prevent the menu from artifacting on the homepage, but it apparently breaks some stuff on android.
