### ISSUE TITLE
Case Study > Code audit

### ISSUE THREAD

**Issue by tpatton89** [BraveUX/braveux#214]
Remove legacy code, update case studies for smoother loading transitions

**Comment by ekfuhrmann** [comment]
A bonus that came along with lazy-loading is that sections are given the proper heights now. This was actually impacting a lot of content across the site that would specifically animate in from the `bottom`. Since I am now calculating an img height ratio, sections have a defined height and can animate from `bottom` as was initially intentioned.

In addition, I've smoothed out a bunch of animations across the site so that sections look and feel much better to scroll through.
