### ISSUE TITLE
Home - SVG path animations

### ISSUE THREAD

**Issue by theseangoodwin** [BraveUX/braveux#216]
We should probably ease these, instead of a linear curve.

**Comment by ekfuhrmann** [comment]
@theseangoodwin So I took a look at the spec to see whether or not we could change up the timing a bit. Turns out they do have a few built-in timing features (ease, ease-in, ease-out, etc.) so I added just a simple ease to the animation. It definitely does give it a more authentic feel.

Let me know what you think.

**Comment by theseangoodwin** [comment]
Looks a lot better. Would `ease-in-out` work there? That would help give it a little more weight.

**Comment by ekfuhrmann** [comment]
Unfortunately it doesn't support an `ease-in-out` timing, or I think that'd be best too. `ease-in` is decent as it starts the stroke slowly and then speeds up, but honestly of the options I feel like `ease` is the best.

**Comment by theseangoodwin** [comment]
Good looks. Thanks Eric!
