### ISSUE TITLE
Responsum Case Study - Wrong Quote Style

### ISSUE THREAD

**Issue by theseangoodwin** [BraveUX/braveux#231]
This is a general change that we'll need to ensure, but we shouldn't be using the 100% width quote, instead we should be generally using the 50/50 style.

**Comment by ekfuhrmann** [comment]
I'm not sure what direction we're choosing to go with this. Since this quote style is approved during the design phase, I'm going to assign this over to @theastralj to provide further clarity. If we are doing away with all full-size quotes, we'll need to audit our case studies and come up with a color scheme for each one.

**Comment by ekfuhrmann** [comment]
We just swapped over Collaboarte to single column.

I think at this point in time, we should try and prioritize using a 50/50 layout, but should have the flexibility to use a single column setup when necessary.

**Comment by theastralj** [comment]
Responsum should be a 50/50 style - as should Gray Langur, etc.

For Responsum, the pullquote would be: To say that Brave UX took our concept to “another level” doesn’t do it justice.

For Gray Langur, the pullquote would be:  It’s not often you come across a team that is so perfectly synced and organized
