### ISSUE TITLE
Stretch Brand Case Study: Taking Stretch Live loading 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#276]
<img width="1325" alt="screen shot 2017-12-06 at 1 07 42 pm" src="https://user-images.githubusercontent.com/31738798/33677377-8c547fe6-da86-11e7-8035-4a068d3b632a.png">

Delayed loading of that left side of the screen

**Comment by ekfuhrmann** [comment]
It always loads the content when the content hits `90%` of the viewport. This means for vertically larger sections, it will take slightly longer before animating.

I don't think this should be changed at this current time since we'd have to make exceptions across the whole site depending on content, rather than just using a universal rule.
