### ISSUE TITLE
Stretch Brand Case Study: Get Your Viewers Into Action 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#278]
<img width="1107" alt="screen shot 2017-12-06 at 1 13 01 pm" src="https://user-images.githubusercontent.com/31738798/33677564-3cd6e9f8-da87-11e7-95cd-cbe6d8b13868.png">
Purple banner is covering copy

**Comment by ekfuhrmann** [comment]
This was based on the design template, though I do agree it's hard to tell whether it's part of the page or still an image in this particular example due to how tall it is.

To make it easier, I've added a subtle drop-shadow to the wave on the bottom so that you can tell that the content is supposed to go behind it, rather than be unsure whether or not you're missing something you were supposed to be reading.
