### ISSUE TITLE
iConstituent Case Study: ALL images and snippets 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#322]
<img width="1299" alt="screen shot 2018-02-07 at 11 17 52 am" src="https://user-images.githubusercontent.com/31738798/35927425-ac266282-0bf8-11e8-96e8-4e7a6ccf8739.png">

<img width="1233" alt="screen shot 2018-02-07 at 11 20 04 am" src="https://user-images.githubusercontent.com/31738798/35927501-e15d57c6-0bf8-11e8-8ef3-8ed2ba10f992.png">

Could we have this in higher resolution? Not sure if this is possible because I remember for the Rokt UXPL it wasn't entirely possible

**Comment by jennabillingsley** [comment]
@ekfuhrmann this one is in your court. happy to export anything as needed.

**Comment by ekfuhrmann** [comment]
This is partially due to the quality of image inside of sketch. A great example is the **A quick show of hands** section. If you blow up the 2 documents here to `2000px` width, you'll notice that it is really aliased and hard to read, specifically the back document:

![image](https://user-images.githubusercontent.com/8878152/36118686-ebbf834e-100b-11e8-8db5-c900ff3d0278.png)

I try to minimize the file as much as possible while preserving fidelity, but in some of these case studies the images we're working with are lower quality to begin with, impacting the quality that eventually makes it to the site.

@theseangoodwin, @jennabillingsley 
We use 2x images on the site, so while it may look passable in Sketch, it needs to be good quality at twice the size we design in. Is there any way we can up the quality of some of these images in the Sketch file?

**Comment by jennabillingsley** [comment]
@ekfuhrmann check the design file for images. The letter is also in the Case Study Screens and can be exported at higher quality

**Comment by ekfuhrmann** [comment]
I went through and updated the images to the original assets used in sketch. For this case study in particular, it didn't make all that large of a difference, but some of the other case studies benefited quite well from using the original assets
