### ISSUE TITLE
gCrit case study: background streaks 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#333]
<img width="316" alt="screen shot 2018-02-07 at 5 43 18 pm" src="https://user-images.githubusercontent.com/31738798/35945495-6b7ad002-0c2e-11e8-8103-f3ba2e48affc.png">

looks sliiiiiightly streaky near that right hand border (down to the wire page) 

Same thing on 
- breathtaking views page
- from pocket to drafting table section 
- a work mixer

**Comment by ekfuhrmann** [comment]
I believe what you're talking about is the `banding` that occurs with the drop-shadow. This will vary from monitor to monitor and is very, very difficult to resolve across all devices since so much of it depends on screen pixel-density, screen calibration, and numerous other variables that we can't control. You will oftentimes be able to see this same effect within gradients as well.

There is not much I can do to minimize this effect beyond what I currently have implemented unfortunately.
