### ISSUE TITLE
DL Case Study: divider after "built to inspire" 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#341]
<img width="1536" alt="screen shot 2018-02-08 at 9 39 50 am" src="https://user-images.githubusercontent.com/31738798/35978552-0b709e86-0cb4-11e8-9a3d-a75261e82c4e.png">

I feel like this divider needs some more context? Or maybe it's not meant to be a divider? It's just that the quote is misleading and upon first reading it I thought it was a testimonial quote. Also, the divider looks like it's part of the case study design itself and not necessarily the DL design - this could just be because the divider has actual DL content on it that could be mistaken for the case study content.

**Comment by theseangoodwin** [comment]
This divider helps to keep rhythm and context moving through the case study.

@ekfuhrmann I do think the quotes on this need to stagger (with the 'Jordan' quote, then the 'Irwin' quote).

**Comment by ekfuhrmann** [comment]
@theseangoodwin You got it. Before they would stagger naturally due to scroll, but there was a possibility of a user refreshing or scrolling quickly causing them both to reveal simultaneously. Now they will naturally stagger like before, but also force a stagger in the instance they are both called at the same time.
