### ISSUE TITLE
MOBILE iConstituent Case Study: 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#351]
<img width="468" alt="screen shot 2018-02-08 at 10 28 31 am" src="https://user-images.githubusercontent.com/31738798/35981270-da54dd92-0cba-11e8-80ed-6bcdfe9d0daf.png">

iphone x safari
The caption bubbles on the divider do not load

**Comment by ekfuhrmann** [comment]
The lines animate 20% from when that container comes into view, while the bubbles appear around 40% of the vh. If you were looking at the animation like you have in the screenshot, the bubbles may not have been called yet?

I'm unsure because when I tested I see the following:

![image](https://user-images.githubusercontent.com/8878152/36108957-00a12530-0fec-11e8-8416-d998ebc24474.png)
