### ISSUE TITLE
MOBILE iConstituent Case Study: Snap polls 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#353]
<img width="652" alt="screen shot 2018-02-08 at 10 32 59 am" src="https://user-images.githubusercontent.com/31738798/35981540-7897322a-0cbb-11e8-9704-599f37be4160.png">

iPhone x safari
the snap polls portion doesn't load until you're AT least half way up the screen

**Comment by ekfuhrmann** [comment]
The animation, if scrolled slowly, appears as it should; however due to browserstack latency and virtual machine, it may look like it takes longer for it to register your scroll position.

For something like this, testing on an actual physical device will provide far greater insight to the animation speed since browser stack can't render it well for testing.
