### ISSUE TITLE
MOBILE iConstituent case study: a positive ID image animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#354]
<img width="636" alt="screen shot 2018-02-08 at 10 34 08 am" src="https://user-images.githubusercontent.com/31738798/35981597-a3745b3a-0cbb-11e8-9640-2aabda1cb6b0.png">

The animation appears to break the image

**Comment by ekfuhrmann** [comment]
This seems to be due to that devices emulation. It's a rather a new emulation they've added, and it has a whole host of other issues I won't get into, but over time the quality really degrades and the screen just begins to artifact.

On a fresh start, I was able to scroll down to the section and ensure that it does indeed render correctly on normal devices:

![image](https://user-images.githubusercontent.com/8878152/36112144-ad9b6f20-0ff6-11e8-85f2-2e2c3ff194f5.png)
