### ISSUE TITLE
Hurdlr Case Study MOBILE: Divider w/ animated icons 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#422]
![Screen Shot 2018-03-27 at 1.56.38 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/0e1fa60d-a8c9-4eb4-b93e-c3c9cc31667f)

The icons are dispersed oddly.

**Comment by ekfuhrmann** [comment]
Yep, this is an odd instance. So to explain, generally we scale the images/icons based on the display size. In this case we have a `min-height` of `35vh` or (35% of the view height of the device). This is done so that we're not left with a super small divider.

On an iPhone X, this is how the section currently looks:
![image](https://user-images.githubusercontent.com/8878152/38036663-3575acf8-3275-11e8-92c2-ee12a3d0f58a.png)

As an alternative approach we can have the following:
![image](https://user-images.githubusercontent.com/8878152/38036689-422055de-3275-11e8-8e5f-df51829e9004.png)

Personally I feel the latter option, while displaying the image better, is too small to work as a divider. I'm not sure how we resolve this without modifying the actual placement on mobile... but due to the way in which we animate and load these it's not a trivial thing.

I'm not sure we get enough mobile traffic to consider really updating this section. I think the larger divider works better, though is absolutely not a best-case scenario. That said, the mobile experience of our case studies is pretty poor as is with content that can be very small.

Going to punt this discussion over to the designers for their thoughts, but to me I think as it currently exists is the best option.
