### ISSUE TITLE
Hurldr Case Study MOBILE: divider with notification animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#425]
![Screen Shot 2018-03-27 at 2.01.09 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/6152952d-a25e-4cd5-acbb-8743ba2b3109)

iphone x
This is not accurate to the desktop version (ie inaccurate colors) and then the animation didn't occur properly (though that could be due to browser stack)

also, it's not vertically centered

**Comment by ekfuhrmann** [comment]
The color issue was due to the way in which safari renders gradients. The gradient was really difficult to see in the first place so I just nixed it in place of solid colors which do render as expected.

That said, WTF safari. I couldn't figure out how to get this to work despite following all of the suggested patterns for Safari. It seems like there is a bug with rendering the gradient as an inline element because I couldn't find this same issue when pasting the SVG into something like codepen.

**Comment by ekfuhrmann** [comment]
I've revisited this thing because it was bothering me so much. It turns out that for some reason [safari requires an absolute href in order to render the gradients correctly](https://stackoverflow.com/questions/18259032/using-base-tag-on-a-page-that-contains-svg-marker-elements-fails-to-render-marke/18265336#18265336). With this knowledge, I was able to re-apply the gradients.
